//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Models.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Models.MarketData]
        ///GO
        ///SET ANSI_NULLS OFF
        ///GO
        ///SET QUOTED_IDENTIFIER OFF
        ///GO
        ///CREATE procedure [dbo].[sp_add_strategy] (
        ///	@bidPrice decimal(18, 2),
        ///	@bidSize decimal (18, 2),
        ///	@askPrice decimal (18, 2),
        ///	@askSize decimal (18, 2),
        ///	@Sequence bigint 
        ///) 
        ///AS
        ///BEGIN
        ///
        ///    SET NOCOUNT ON
        ///
        ///    /*
        ///    ** Declarations.
        ///    */
        ///    DECLARE @retcode int=0
        ///            
        ///	-- CREATE TREND ENTRY -- 
        ///	--check if current trend
        ///	DECLARE @t_id INTEGER=NULL
        ///	DECLARE @t_trendType INTEGER=NULL
        ///
        ///	-- Status [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_add_strategy {
            get {
                return ResourceManager.GetString("Create_sp_add_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USE [Models.MarketData]
        ///GO
        ///SET ANSI_NULLS OFF
        ///GO
        ///SET QUOTED_IDENTIFIER OFF
        ///GO
        ///CREATE procedure [dbo].[sp_add_trend] (
        ///	@bidPrice decimal(18, 2),
        ///	@bidSize decimal (18, 2),
        ///	@askPrice decimal (18, 2),
        ///	@askSize decimal (18, 2),
        ///	@Sequence bigint 
        ///) 
        ///AS
        ///BEGIN
        ///
        ///    SET NOCOUNT ON
        ///
        ///    /*
        ///    ** Declarations.
        ///    */
        ///    DECLARE @retcode int=0
        ///            
        ///	-- CREATE TREND ENTRY -- 
        ///	--check if current trend
        ///	DECLARE @t_id INTEGER=NULL
        ///	DECLARE @t_trendType INTEGER=NULL
        ///
        ///	-- Status va [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_sp_add_trend {
            get {
                return ResourceManager.GetString("Create_sp_add_trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER [dbo].[tr_WatchStrategy]  ON dbo.Strategies AFTER INSERT
        ///AS  
        ///DECLARE @StrategyID 		AS int 
        ///DECLARE @Type 			AS int
        ///DECLARE @Status 		AS int 
        ///
        ///SELECT @StrategyId 	= StrategyId,		
        ///       @Type 		= Type,
        ///       @Status 		= Status 	
        ///FROM INSERTED	   
        ///
        ///
        ///GO.
        /// </summary>
        internal static string Create_tr_WatchStrategy {
            get {
                return ResourceManager.GetString("Create_tr_WatchStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER [dbo].[tr_WatchTicker]  ON dbo.Tickers AFTER INSERT
        ///AS  
        ///
        ///DECLARE	@bidPrice AS decimal(18, 2)
        ///DECLARE	@bidSize  AS decimal(18, 2)
        ///DECLARE	@askPrice AS decimal(18, 2)
        ///DECLARE	@askSize  AS decimal(18, 2)
        ///DECLARE	@Sequence AS bigint 
        ///
        ///SELECT @bidPrice = bidPrice,
        ///	   @bidSize  = bidSize ,
        ///	   @askPrice = askPrice,
        ///	   @askSize  = askSize ,
        ///	   @Sequence = Sequence
        ///	   FROM inserted
        ///
        ///EXEC [dbo].[sp_add_trend] @bidPrice, @bidSize,	@askPrice,	@askSize, @Sequence 
        ///
        ///GO.
        /// </summary>
        internal static string Create_tr_WatchTicker {
            get {
                return ResourceManager.GetString("Create_tr_WatchTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TRIGGER [dbo].[tr_WatchTrend]  ON dbo.Trends AFTER INSERT, UPDATE
        ///AS  
        ///DECLARE @TrendId 		AS int 
        ///DECLARE @StartSequence 	AS bigint 
        ///DECLARE @EndSequence 	AS bigint 
        ///DECLARE @StartBidPrice 	AS real 
        ///DECLARE @EndBidPrice 	AS real 
        ///DECLARE @StartAskPrice 	AS real 
        ///DECLARE @EndAskPrice 	AS real 
        ///DECLARE @Type 			AS int
        ///DECLARE @Status 		AS int 
        ///
        ///SELECT @TrendId 		= TrendId,		
        ///       @StartSequence 	= StartSequence 	,
        ///       @EndSequence 	= EndSequence 	,
        ///       @StartBidPrice 	= StartBidP [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Create_tr_WatchTrend {
            get {
                return ResourceManager.GetString("Create_tr_WatchTrend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TRIGGER [dbo].[sp_add_strategy].
        /// </summary>
        internal static string Drop_sp_add_strategy {
            get {
                return ResourceManager.GetString("Drop_sp_add_strategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TRIGGER [dbo].[sp_add_trend].
        /// </summary>
        internal static string Drop_sp_add_trend {
            get {
                return ResourceManager.GetString("Drop_sp_add_trend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TRIGGER [dbo].[tr_WatchStrategy].
        /// </summary>
        internal static string Drop_tr_WatchStrategy {
            get {
                return ResourceManager.GetString("Drop_tr_WatchStrategy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TRIGGER [dbo].[tr_WatchTicker].
        /// </summary>
        internal static string Drop_tr_WatchTicker {
            get {
                return ResourceManager.GetString("Drop_tr_WatchTicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DROP TRIGGER [dbo].[tr_WatchTrend].
        /// </summary>
        internal static string Drop_tr_WatchTrend {
            get {
                return ResourceManager.GetString("Drop_tr_WatchTrend", resourceCulture);
            }
        }
    }
}
