// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createtriggeronorder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtriggeronorder));
        
        string IMigrationMetadata.Id
        {
            get { return "201908272049124_create-trigger-on-order"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
