// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createtriggeronticker : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtriggeronticker));
        
        string IMigrationMetadata.Id
        {
            get { return "201908242301121_create-trigger-on-ticker"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
