// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class createtriggerondownupstrategy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(createtriggerondownupstrategy));
        
        string IMigrationMetadata.Id
        {
            get { return "201908272154344_create-trigger-on-down-up-strategy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
