// <auto-generated />
namespace Models.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class creatependingrequeststable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(creatependingrequeststable));
        
        string IMigrationMetadata.Id
        {
            get { return "201909032048531_create-pending-requests-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
